config/routes.rb
Rails.application.routes.draw do
  root to: "routes#index"

  resources :products
  resources :criteria_definitions
  resources :routes, only: [:index] do
    collection do
      match "search", action: :search, via: [:get, :post]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/criteria_definition.rb
class CriteriaDefinition < ApplicationRecord

  validates :destination, presence: true
  validates :max_price, numericality: true, format: { with: /\A\d{1,6}(\.\d{1,2})?\z/ }, allow_nil: true
  validates_uniqueness_of :references, scope: [:categories, :max_price],
    message: "not unique in the scope of Categories and Max price"

  before_validation :strip_and_sort_array_fields

  # Used to determine the best fitting criteria_definition for a product
  def degree_of_specificity
    [references, categories, max_price].map do |attribute|
      attribute.blank? ? 0 : 1
    end.sum
  end

  private

  def strip_and_sort_array_fields
    [:references, :categories].each do |attribute|
      if self[attribute].present?
        value = self[attribute].map(&:strip).reject(&:blank?)&.sort
        self[attribute] = value.blank? ? nil : value
      end
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  self.primary_key = :reference

  validates :reference, :name, :category, :price, presence: true
  validates :price, numericality: true, format: { with: /\A\d{1,6}(\.\d{1,2})?\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/criteria_definitions_controller.rb
class CriteriaDefinitionsController < ApplicationController

  before_action :set_criteria_definition, only: [:show, :edit, :update, :destroy]

  def index
    @criteria_definitions = CriteriaDefinition.all
  end

  def new
    @criteria_definition = CriteriaDefinition.new
  end
  
  def create
    @criteria_definition = CriteriaDefinition.new(criteria_definition_params)
    if @criteria_definition.save
      redirect_to criteria_definition_path(@criteria_definition)
    else
      flash[:error] = "Criteria definition not valid: #{@criteria_definition.errors.full_messages.join(", ")}"
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @criteria_definition.update(criteria_definition_params)
      redirect_to criteria_definition_path(@criteria_definition)
    else
      flash[:error] = "Criteria definition not valid: #{@criteria_definition.errors.full_messages.join(", ")}"
      render :edit
    end
  end
  
  def destroy
    @criteria_definition.destroy
    flash[:success] = "Criteria definition #{@criteria_definition.id} deleted"
    redirect_to criteria_definitions_path
  end

  private

  def criteria_definition_params
    params.require(:criteria_definition).permit(
      { references: [] },
      { categories: [] },
      :max_price,
      :destination
    )
  end

  def set_criteria_definition
    @criteria_definition = CriteriaDefinition.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.order(:reference)
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      flash[:error] = "Product not valid: #{@product.errors.full_messages.join(", ")}"
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      flash[:error] = "Product not valid: #{@product.errors.full_messages.join(", ")}"
      render :edit
    end
  end
  
  def destroy
    @product.destroy
    flash[:success] = "Product #{@product.reference} deleted"
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(
      :reference,
      :name,
      :category,
      :price
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  def index
  end

  def search
    if params[:reference]
      reference = params[:reference].strip
      product = Product.find_by_reference(reference)
      if product.nil?
        flash[:error] = "Product \"#{reference}\" not found"
      else
        @router = Router.new(product)
      end
    end

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash.each do |type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(type)}", role: "alert") do 
        concat content_tag(:button, "x", class: "close", data: { dismiss: "alert" })
        concat message 
      end)
    end
    nil
  end

  def bootstrap_class_for(type)
    case type.to_sym
    when :notice
      "alert-info"
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert
      "alert-warning"
    end
  end
end

app/views/criteria_definitions/_form.html.erb
<%= form_for(criteria_definition) do |f| %>
  <div class="form-group">
    <%= f.label :references %>
    <%= f.text_field :references, name: "criteria_definition[references][]", value: criteria_definition.references&.join(", "), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :categories %>
    <%= f.text_field :categories, name: "criteria_definition[categories][]", value: criteria_definition.categories&.join(", "), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :max_price %>
    <%= f.text_field :max_price, class: "form-control" %>
  </div>

  <div class="form-group required">
    <%= f.label :destination %>
    <%= f.text_field :destination, class: "form-control", required: true %>
  </div>

  <%= f.submit submit_text || "Submit", class: "btn btn-primary" %>
<% end %>

app/views/criteria_definitions/edit.html.erb
<h1>Edit criteria definition <%= @criteria_definition.id %></h1>

<%= render "form", criteria_definition: @criteria_definition, submit_text: "Update criteria definition" %>

app/views/criteria_definitions/index.html.erb
<h1>Criteria definitions list</h1>

<% if @criteria_definitions.empty? %>
  <p>There are no criteria definitions... Maybe <a href="<%= new_criteria_definition_path %>">create a new one?</a></p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">References</th>
        <th scope="col">Categories</th>
        <th scope="col">Max price</th>
        <th scope="col">Destination</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @criteria_definitions.each do |criteria_definition| %>
        <tr>
          <th scope="row"><%= link_to criteria_definition.id, criteria_definition_path(criteria_definition) %></th>
          <td><%= criteria_definition.references&.join(", ") %></td>
          <td><%= criteria_definition.categories&.join(", ") %></td>
          <td><%= criteria_definition.max_price %></td>
          <td><%= criteria_definition.destination %></td>
          <td><a href="<%= edit_criteria_definition_path(criteria_definition) %>"><button type="button" class="btn btn-primary btn-sm">Edit</button></a></td>
          <td><%= button_to "Destroy", criteria_definition_path(criteria_definition), method: :delete, data: { confirm: "Are you sure you want to delete #{criteria_definition.id}?" }, class: "btn btn-sm btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/criteria_definitions/new.html.erb
<h1>New criteria definition</h1>

<%= render "form", criteria_definition: @criteria_definition, submit_text: "Create criteria definition" %>

app/views/criteria_definitions/show.html.erb
<div class="card mt-4">
  <h5 class="card-header">
    Criteria definition <%= @criteria_definition.id %>
  </h5>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      References: <%= @criteria_definition.references&.join(", ") %>
    </li>
    <li class="list-group-item">
      Categories: <%= @criteria_definition.categories&.join(", ") %>
    </li>
    <li class="list-group-item">
      Max price: <%= number_to_currency(@criteria_definition.max_price, unit: "€") %>
    </li>
    <li class="list-group-item">
      Destination: <%= @criteria_definition.destination %>
    </li>
  </ul>
</div>

<div class="mt-4">
  <a href="<%= edit_criteria_definition_path(@criteria_definition) %>">
    <button type="button" class="btn btn-primary btn-sm">Edit</button>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "shared/navigation" %>

  <body>
    <div class="container">
      <%= flash_messages %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <div class="form-group required">
    <%= f.label :reference %>
    <%= f.text_field :reference, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
    <small class="form-text text-muted">Use "." as a separator</small>
  </div>

  <%= f.submit submit_text || "Submit", class: "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product <%= @product.reference %></h1>

<%= render "form", product: @product, submit_text: "Update product" %>

app/views/products/index.html.erb
<h1>Products list</h1>

<% if @products.empty? %>
  <p>There are no products... Maybe <a href="<%= new_product_path %>">create a new one?</a></p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Reference</th>
        <th scope="col">Name</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <th scope="row"><%= link_to product.reference, product_path(product) %></th>
          <td><%= product.name %></td>
          <td><%= product.category %></td>
          <td><%= number_to_currency(product.price, unit: "€") %></td>
          <td><a href="<%= edit_product_path(product) %>"><button type="button" class="btn btn-primary btn-sm">Edit</button></a></td>
          <td><%= button_to "Destroy", product_path(product), method: :delete, data: { confirm: "Are you sure you want to delete #{product.reference}?" }, class: "btn btn-sm btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product, submit_text: "Create product" %>

app/views/products/show.html.erb
<div class="card mt-4">
  <h5 class="card-header">
    Product <%= @product.reference %>
  </h5>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      Name: <%= @product.name %>
    </li>
    <li class="list-group-item">
      Category: <%= @product.category %>
    </li>
    <li class="list-group-item">
      Price: <%= number_to_currency(@product.price, unit: "€") %>
    </li>
  </ul>
</div>

<div class="mt-4">
  <a href="<%= edit_product_path(@product) %>">
    <button type="button" class="btn btn-primary btn-sm">Edit</button>
  </a>
</div>

app/views/routes/index.html.erb
<h1>Routes</h1>

<h5>Search by product reference</h5>

<%= form_tag "/routes/search" do %>
  <div class="form-group required">
    <%= label_tag :reference %>
    <%= text_field_tag :reference, @router&.product&.reference, { class: "form-control", required: true } %>
  </div>

  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<% if @router %>
  <div class="card mt-4">
    <h5 class="card-header">
      Destination: <%= @router.criteria_definition&.destination || "Not found!" %>
    </h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Product: <a href="<%= product_path(@router.product) %>"><%= "#{@router.product.reference} - #{@router.product.name}" %></a>
      </li>
      <% if @router.criteria_definition %>
        <li class="list-group-item">Criteria definition:
          <a href="<%= criteria_definition_path(@router.criteria_definition) %>"><%= @router.criteria_definition.id %></a>
          (references: <%= @router.criteria_definition.references&.join(", ") || "null" %> | categories: <%= @router.criteria_definition.categories&.join(", ") || "null" %> | max_price: <%= number_to_currency(@router.criteria_definition.max_price, unit: "€") || "null" %>)
        </li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= routes_path %>">Warehouse</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="products-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="products-dropdown">
          <a class="dropdown-item" href="<%= products_path%>">Index</a>
          <a class="dropdown-item" href="<%= new_product_path%>">New</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="criteria-definitions-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Criteria definitions
        </a>
        <div class="dropdown-menu" aria-labelledby="criteria-definitions-dropdown">
          <a class="dropdown-item" href="<%= criteria_definitions_path%>">Index</a>
          <a class="dropdown-item" href="<%= new_criteria_definition_path%>">New</a>
        </div>
      </li>
    </ul>
  </div>
</nav>